---
- hosts: all
  tasks:
  - name: Installing dependencies for yum
    yum:
      name: python3-dnf
      state: present

  - name: Update all installed packages using YUM module
    um:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: yum_update_status

  - debug: var=yum_update_status

  - name: Remove packates not needed anymore
    yum:
      autoremove: yes

  - name: Reboot when packages were updated
    reboot:
    when: yum_update_status.changed
